### ISSUE TITLE
Deprecation of --process-dependency-links

### ISSUE THREAD

**Issue by thegeorgeous** [libindic/scriptrender#9]
Since v1.5, `pip` no longer respects `--process-dependecy-links` and it must be explicitly declared by the user. Considering that the version of `pypdflib` used in `libindic` is a advanced fork, releasing it under different name in pypi maybe necessary for continued development
https://github.com/pypa/pip/blob/develop/CHANGES.txt#L791

**Comment by copyninja** [comment]
So this is closed by your PR right?
